CREATE PROCEDURE [dbo].[PURGE_SQL_AGENT_HISTORY]
	@RETAIN_HISTORY_DAYS INT
AS
BEGIN
	DECLARE 
		@MIN_DATE	DATE 
	,	@INT_DATE	INT;
	
	SET @MIN_DATE = DATEADD(day, @RETAIN_HISTORY_DAYS * -1, GETDATE());
	SET @INT_DATE = FORMAT(@MIN_DATE, 'yyyyMMdd');

	DELETE [dbo].[JOB_HISTORY]
	WHERE [run_date] < @INT_DATE;
END

