CREATE TABLE [dbo].[STATE]
(
	[STATE_ID]		BIGINT NOT NULL PRIMARY KEY CLUSTERED
		CONSTRAINT DF_STATE_STATE_ID 
			DEFAULT NEXT VALUE FOR [dbo].[STATE_ID_SEQUENCE]
,	[NAME]			NVARCHAR(50) NOT NULL
,	[CUSTOM_STATE]	NVARCHAR(4000) NULL
,	[LAST_MODIFIED]	DATETIME NOT NULL
		CONSTRAINT DF_STATE_LAST_MODIFIED 
			DEFAULT GETDATE()
)
