CREATE PROCEDURE [dbo].[GET_END_JOB_INSTANCE_ID]
AS
BEGIN
	DECLARE @MAX_JOB_INSTANCE_ID INT = NULL;

	SELECT
		@MAX_JOB_INSTANCE_ID = MAX([instance_id])
	FROM [msdb].[dbo].[sysjobhistory];
	
	SELECT COALESCE(@MAX_JOB_INSTANCE_ID, 0);	
END